#!/usr/bin/env python3
"""Auto-publish top YW candidate as AI-Trader signal.

Called by apex-bootcamp GHA after YW daily reminder.
Reads the latest grades-{date}.json from yw_daily output,
picks the top actionable candidate (highest priority_score, A/B grade),
publishes as a strategy signal to ai4trade.ai.

Usage:
  python3 publish_signal.py [--date YYYY-MM-DD] [--dry-run]
"""
import os
import sys
import json
import argparse
from pathlib import Path
import requests

CRED = Path(__file__).parent / "CREDENTIALS.json"
CRED_ENV = os.environ.get("AI_TRADER_CRED")
if CRED_ENV:
    CRED = Path(CRED_ENV)
LOG = Path(__file__).parent / "publish_signal.log"
API_BASE = "https://ai4trade.ai/api"


def load_credentials() -> dict:
    return json.loads(CRED.read_text())


def find_latest_grades(yw_repo_dir: str, date: str | None = None) -> Path | None:
    """Find the latest grades-{date}.json."""
    base = Path(yw_repo_dir) / "automation" / "reports" / "daily"
    if date:
        f = base / date / f"grades-{date}.json"
        return f if f.exists() else None
    # Find latest by directory
    if not base.exists():
        return None
    days = sorted([d for d in base.iterdir() if d.is_dir()], reverse=True)
    for d in days:
        candidates = list(d.glob("grades-*.json"))
        if candidates:
            return candidates[0]
    return None


def format_signal_content(candidate: dict) -> dict:
    """Format a candidate dict into AI-Trader signal payload."""
    strategy = candidate["strategy"]
    ticker = candidate["ticker"]
    grade = candidate["grade"]
    score = candidate["priority_score"]
    reason = candidate.get("reason", "")[:300]
    direction = candidate.get("direction", "long")

    title = f"{ticker} {strategy} [{grade}] (Score {score:.0f})"

    # For futures: $100 SL, $150 TP (1.5 RR)
    content = f"""**Ticker**: {ticker}
**Strategy**: {strategy}
**Grade**: {grade} (Score {score:.1f})
**Direction**: {direction}
**Size**: {"1.0µ" if grade == "A" else "0.5µ" if grade == "B" else "skip"}
**SL**: ~$100 (50pt MNQ / 10pt MGC)
**TP**: $150 (1.5 RR)

**Reasoning**:
{reason}

**Source**: YW Concept daily reminder (apex-bootcamp v2.6.8)
**Generated by**: Mavis-Apex-YW-Bot agent
"""

    tags = ["yw-concept", strategy.lower(), direction, "mnq" if "MNQ" in ticker else "mes" if "MES" in ticker else "m2k"]
    return {
        "market": "futures",
        "title": title[:100],
        "content": content[:1500],
        "symbols": ticker,
        "tags": ",".join(tags),
    }


def publish_signal(token: str, payload: dict) -> dict:
    """POST to /api/signals/strategy."""
    r = requests.post(
        f"{API_BASE}/signals/strategy",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json=payload,
        timeout=15,
    )
    r.raise_for_status()
    return r.json()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--date", help="Specific date YYYY-MM-DD")
    parser.add_argument("--yw-repo", default="/workspace/YW-concept-ki7409",
                        help="Path to YW repo")
    parser.add_argument("--dry-run", action="store_true", help="Don't actually publish")
    args = parser.parse_args()

    cred = load_credentials()
    token = cred["token"]
    agent_name = cred["name"]
    print(f"[publish] Agent: {agent_name} (id={cred['agent_id']})")

    grades_path = find_latest_grades(args.yw_repo, args.date)
    if not grades_path:
        print(f"[publish] ❌ No grades file found in {args.yw_repo}")
        return 1
    print(f"[publish] Reading: {grades_path}")

    data = json.loads(grades_path.read_text())
    candidates = data.get("candidates", [])
    actionable = [c for c in candidates if c.get("actionable") and c.get("grade") in ("A", "B")]

    if not actionable:
        print(f"[publish] ⚠️  No actionable A/B candidates today. Skip.")
        return 0

    # Pick the top by priority_score
    top = sorted(actionable, key=lambda c: c["priority_score"], reverse=True)[0]
    print(f"[publish] Top candidate: {top['strategy']} on {top['ticker']} "
          f"[{top['grade']}] score={top['priority_score']:.1f}")

    payload = format_signal_content(top)
    print(f"[publish] Title: {payload['title']}")
    print(f"[publish] Content length: {len(payload['content'])} chars")

    if args.dry_run:
        print(f"[publish] 🧪 DRY-RUN mode. Skipping actual publish.")
        print(f"[publish] Payload preview:\n{json.dumps(payload, indent=2, ensure_ascii=False)[:800]}")
        return 0

    try:
        result = publish_signal(token, payload)
        success = result.get("success", False)
        signal_id = result.get("signal_id", "?")
        points = result.get("points_earned", 0)
        log_line = (f"[{Path(__file__).name}] {grades_path.parent.name} "
                    f"signal_id={signal_id} points={points} success={success}")
        with LOG.open("a") as f:
            f.write(log_line + "\n")
        print(f"[publish] ✅ Published: signal_id={signal_id}, earned {points} points")
        return 0 if success else 1
    except Exception as e:
        err = f"[publish] ❌ {e}"
        print(err, file=sys.stderr)
        with LOG.open("a") as f:
            f.write(err + "\n")
        return 1


if __name__ == "__main__":
    sys.exit(main())
